import swatImg from '../assets/swat.jpg';
import naranImg from '../assets/naran.jpg';
import montenegroImg from '../assets/montenegro.jpg';
import bangkokImg from '../assets/bangkok.jpg';
import hunzaImg from '../assets/hunza.jpg';
import nathiagaliImg from '../assets/nathiagali.jpg';
import saudiarabiaImg from '../assets/saudiarabia.jpg';
import scotlandImg from '../assets/scotland.jpg';
import bakuImg from '../assets/baku.jpg';

export const tours = [
  {
    id: 1,
    title: "Baku Group Tour Package",
    type: "international-group",
    category: "Cultural",
    image: bakuImg,
    duration: "5 Days",
    rating: 4.8,
    reviews: 115,
    price: 233800,
    currency: "PKR",
    description: "Explore the stunning architecture of Baku, Azerbaijan. Visit the iconic Flame Towers, Heydar Aliyev Center, and walk the historic streets of Old Town (Icherisheher).",
    highlights: ["Heydar Aliyev Center tour", "Flame Towers & Caspian Boulevard walk", "Icherisheher (Old Baku) guided tour", "Gobustan mud volcanoes day trip"]
  },
  {
    id: 2,
    title: "Thailand Honeymoon Private Tour",
    type: "international-private",
    category: "Beach",
    image: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=800&q=80",
    duration: "6 Days",
    rating: 4.9,
    reviews: 242,
    price: 387500,
    currency: "PKR",
    description: "A romantic luxury private getaway across Bangkok and Phuket. Enjoy private beach dinners, scenic island hopping, and explore grand Buddhist temples.",
    highlights: ["Private candlelit beach dinner", "Phi Phi Islands speedboat day trip", "Grand Palace & Wat Pho temple tour", "Couples spa treatment in Phuket"]
  },
  {
    id: 3,
    title: "Kalam & Swat Valley Group Adventure",
    type: "local-group",
    category: "Adventure",
    image: swatImg,
    duration: "4 Days",
    rating: 4.7,
    reviews: 86,
    price: 28500,
    currency: "PKR",
    description: "Witness the magnificent pine forests, gushing Swat River, and glacier lakes. Explore Kalam, Ushu Pine Forest, and the breathtaking Mahodand Lake.",
    highlights: ["Explore lush Ushu Pine Forest", "4x4 Jeep track ride to Mahodand Lake", "Fizagat Park and Swat River walk", "Sightseeing at Malam Jabba ski resort"]
  },
  {
    id: 4,
    title: "Himmel Skardu Premium Private Tour",
    type: "local-private",
    category: "Mountain",
    image: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80",
    duration: "5 Days",
    rating: 4.8,
    reviews: 142,
    price: 73500,
    currency: "PKR",
    description: "An exclusive private retreat to Skardu. Visit Shangrila Resort, experience Katpana Cold Desert dune safari, and view Sadpara Lake with a private guide.",
    highlights: ["Shangrila Resort & Lower Kachura Lake", "Katpana Desert dune safari & campfire", "Kharpocho Fort heritage walk", "Day excursion to Deosai National Plains"]
  },
  {
    id: 5,
    title: "Naran, Hunza & Skardu Grand Group Tour",
    type: "local-group",
    category: "Mountain",
    image: naranImg,
    duration: "11 Days",
    rating: 4.9,
    reviews: 198,
    price: 93500,
    currency: "PKR",
    description: "The ultimate northern Pakistan roadtrip. Traverse Babusar Top, view Nanga Parbat, explore Hunza Valley (Karimabad, Attabad Lake), and discover Skardu.",
    highlights: ["Babusar Pass & Lulusar Lake views", "Attabad Lake boating & jet-ski", "Altit & Baltit ancient fort tours", "Traverse to Cold Desert & Deosai plains"]
  },
  {
    id: 6,
    title: "Europe 3-Countries Grand Group Tour",
    type: "international-group",
    category: "Cultural",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    duration: "7 Days",
    rating: 4.9,
    reviews: 165,
    price: 393500,
    currency: "PKR",
    description: "Tour the historic hearts of France, Germany, and Switzerland. Visit the Eiffel Tower in Paris, explore Heidelberg Castle, and gaze at the Swiss Alps.",
    highlights: ["Eiffel Tower & Seine River Cruise", "Guided tour of Heidelberg Castle", "Scenic drive through the Black Forest", "Mount Titlis cable car excursion"]
  },
  {
    id: 7,
    title: "Japan Private Heritage Tour",
    type: "international-private",
    category: "Cultural",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
    duration: "9 Days",
    rating: 4.9,
    reviews: 215,
    price: 678500,
    currency: "PKR",
    description: "An exclusive private journey through Tokyo, Mount Fuji, and Kyoto. Travel via bullet train and stay in traditional luxury Ryokan inns.",
    highlights: ["Private guide & private vehicle transfers", "Senso-ji Temple & Shibuya Crossing", "Mount Fuji 5th Station panoramic view", "Kyoto tea ceremony & Fushimi Inari trail"]
  },
  {
    id: 8,
    title: "Kashmir & Shogran Valley Group Tour",
    type: "local-group",
    category: "Mountain",
    image: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80",
    duration: "8 Days",
    rating: 4.8,
    reviews: 94,
    price: 56500,
    currency: "PKR",
    description: "Discover the pristine forests of Neelum Valley, walk the lush meadows of Siri Paye, and relax in the beautiful hill station of Shogran.",
    highlights: ["Siri Paye Meadows jeep excursion", "Neelum River bank photography walk", "Keran, Sharda, and Kutton waterfall tours", "Musical bonfire night in Shogran"]
  },
  {
    id: 9,
    title: "Montenegro Private Coast & Alps Tour",
    type: "international-private",
    category: "Beach",
    image: montenegroImg,
    duration: "8 Days",
    rating: 4.8,
    reviews: 73,
    price: 293200,
    currency: "PKR",
    description: "Wander the UNESCO-listed Kotor Bay, explore the rugged Durmitor National Park, and relax on private beaches along the Adriatic Sea.",
    highlights: ["Private yacht tour of Kotor Bay", "Explore old town Budva with local guide", "Hike around Black Lake in Zabljak", "Tara River Canyon zip-lining adventure"]
  },
  {
    id: 10,
    title: "Bangkok & Pattaya Group Tour",
    type: "international-group",
    category: "Beach",
    image: bangkokImg,
    duration: "7 Days",
    rating: 4.7,
    reviews: 132,
    price: 173500,
    currency: "PKR",
    description: "Experience the vibrant city life of Bangkok and the tropical beaches of Pattaya. Includes coral island speed boating and temple tours.",
    highlights: ["Coral Island speedboat trip with lunch", "Alcazar cabaret show tickets", "Wat Arun & Wat Pho temple tour", "Chaophraya River luxury dinner cruise"]
  },
  {
    id: 11,
    title: "Murree & Nathia Gali Private Escape",
    type: "local-private",
    category: "Adventure",
    image: nathiagaliImg,
    duration: "5 Days",
    rating: 4.7,
    reviews: 58,
    price: 46500,
    currency: "PKR",
    description: "Enjoy a cool mountain breeze in the Galliyat region. Wander the quiet walking trails of Nathia Gali, visit Ayubia pipeline tracks, and stay in Murree.",
    highlights: ["Nathia Gali pipeline walking track", "Ayubia chairlift ride & picnic", "Mall Road shopping in Murree", "Private vehicle transfers throughout"]
  },
  {
    id: 12,
    title: "Hunza, Skardu & Chillas Private Safari",
    type: "local-private",
    category: "Mountain",
    image: hunzaImg,
    duration: "10 Days",
    rating: 4.9,
    reviews: 112,
    price: 133200,
    currency: "PKR",
    description: "An exclusive, high-end private safari across the Karakoram. Stay in premium luxury resorts, cross the Hussaini bridge, and tour Karimabad forts.",
    highlights: ["Premium resort stays in Hunza & Skardu", "Private land cruiser Prado transportation", "Attabad Lake private boating tour", "Rakaposhi & Nanga Parbat viewpoints"]
  },
  {
    id: 13,
    title: "Saudi Arabia Sacred Journey & Desert Al-Ula",
    type: "international-private",
    category: "Cultural",
    image: saudiarabiaImg,
    duration: "8 Days",
    rating: 4.9,
    reviews: 88,
    price: 345000,
    currency: "PKR",
    description: "Embark on a premium journey through Makkah, Madinah, and the historic ruins of Al-Ula. Experience authentic Arabian hospitality and explore historic heritage sites.",
    highlights: ["Guided Ziyarat in Makkah & Madinah", "High-speed Haramain Train tickets", "Al-Ula (Hegra UNESCO ruins) tour", "Elephant Rock stargazing dinner"]
  },
  {
    id: 14,
    title: "London & Scottish Highlands Explorer Tour",
    type: "international-group",
    category: "Cultural",
    image: scotlandImg,
    duration: "7 Days",
    rating: 4.8,
    reviews: 104,
    price: 425000,
    currency: "PKR",
    description: "Explore the best of Great Britain. Wander the royal landmarks of London, see prehistoric Stonehenge, and traverse the stunning peaks of the Scottish Highlands.",
    highlights: ["London Eye & Westminster Abbey tour", "Stonehenge & Bath historic day excursion", "Edinburgh Castle guided tour", "Scottish Highlands & Loch Ness cruise"]
  },
  {
    id: 15,
    title: "Swiss Alps & Lucerne Scenic Luxury Tour",
    type: "international-private",
    category: "Mountain",
    image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=80",
    duration: "6 Days",
    rating: 4.9,
    reviews: 142,
    price: 512000,
    currency: "PKR",
    description: "An exquisite Swiss mountain escape. Ride the scenic trains, explore the lakeside beauty of Lucerne, and gaze at the majestic Matterhorn in Zermatt.",
    highlights: ["Lucerne Chapel Bridge walking tour", "Mount Pilatus cogwheel railway ride", "Scenic Glacier Express train pass", "Matterhorn panoramic view in Zermatt"]
  },
  {
    id: 16,
    title: "Maldives Luxury Overwater Villa Resort Escape",
    type: "international-private",
    category: "Beach",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    duration: "5 Days",
    rating: 4.9,
    reviews: 186,
    price: 395000,
    currency: "PKR",
    description: "Stay in a premium overwater villa with direct lagoon access. Enjoy sunset dolphin cruises, private dining on sandbanks, and world-class snorkeling.",
    highlights: ["Luxury overwater villa accommodation", "All-inclusive premium dining & drinks", "Private sandbank sunset dinner", "Guided snorkeling tour of banana reef"]
  },
  {
    id: 17,
    title: "Dubai Group Shopping Festival & City Tour",
    type: "international-group",
    category: "Adventure",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80",
    duration: "5 Days",
    rating: 4.8,
    reviews: 96,
    price: 185000,
    currency: "PKR",
    description: "Discover the glitz and glamour of Dubai. Shop at the world-famous Dubai Mall, experience a desert safari with dune bashing, and view the city from Burj Khalifa.",
    highlights: ["Burj Khalifa 124th Floor entrance", "Desert Safari with dune bashing & BBQ", "Dubai Marina sunset dinner cruise", "Guided old Dubai souk shopping tour"]
  },
  {
    id: 18,
    title: "Malam Jabba Ski Resort Private Trip",
    type: "local-private",
    category: "Adventure",
    image: "https://images.unsplash.com/photo-1605548230624-8d2d0419c517?auto=format&fit=crop&w=800&q=80",
    duration: "3 Days",
    rating: 4.6,
    reviews: 45,
    price: 34500,
    currency: "PKR",
    description: "Enjoy a private snow escape at Malam Jabba, Pakistan's premier ski resort. Perfect for skiing, chairlift rides, and scenic winter sightseeing.",
    highlights: ["Skiing lessons with certified guide", "Ayubia chairlift sightseeing ticket", "Bonfire night at Malam Jabba hotel", "Private vehicle transfers from Islamabad"]
  }
];
