export const tours = [
  {
    id: 1,
    title: "Baku Group Tour Package",
    type: "international",
    category: "Cultural",
    image: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80",
    duration: "5 Days",
    rating: 4.8,
    reviews: 115,
    price: 233800,
    currency: "PKR",
    description: "Explore the stunning architecture of Baku, Azerbaijan. Visit the iconic Flame Towers, Heydar Aliyev Center, and walk the historic streets of Old Town (Icherisheher).",
    highlights: ["Heydar Aliyev Center tour", "Flame Towers & Caspian Boulevard walk", "Icherisheher (Old Baku) guided tour", "Gobustan mud volcanoes day trip"]
  },
  {
    id: 2,
    title: "Thailand Honeymoon Tour Package",
    type: "international",
    category: "Beach",
    image: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=800&q=80",
    duration: "6 Days",
    rating: 4.9,
    reviews: 242,
    price: 387500,
    currency: "PKR",
    description: "A romantic luxury getaway across Bangkok and Phuket. Enjoy private beach dinners, scenic island hopping, and explore grand Buddhist temples.",
    highlights: ["Private candlelit beach dinner", "Phi Phi Islands speedboat day trip", "Grand Palace & Wat Pho temple tour", "Couples spa treatment in Phuket"]
  },
  {
    id: 3,
    title: "Kalam & Swat Valley Adventure",
    type: "local",
    category: "Adventure",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    duration: "4 Days",
    rating: 4.7,
    reviews: 86,
    price: 28500,
    currency: "PKR",
    description: "Witness the magnificent pine forests, gushing Swat River, and glacier lakes. Explore Kalam, Ushu Pine Forest, and the breathtaking Mahodand Lake.",
    highlights: ["Explore lush Ushu Pine Forest", "4x4 Jeep track ride to Mahodand Lake", "Fizagat Park and Swat River walk", "Sightseeing at Malam Jabba ski resort"]
  },
  {
    id: 4,
    title: "Skardu Valley & Desert Safari",
    type: "local",
    category: "Mountain",
    image: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80",
    duration: "5 Days",
    rating: 4.8,
    reviews: 142,
    price: 43500,
    currency: "PKR",
    description: "Immerse yourself in the stunning high-altitude scenery of Baltistan. Visit Shangrila Resort, ATV ride on Katpana Cold Desert, and view Sadpara Lake.",
    highlights: ["Shangrila Resort & Lower Kachura Lake", "Katpana Desert dune safari & campfire", "Kharpocho Fort heritage walk", "Day excursion to Deosai National Plains"]
  },
  {
    id: 5,
    title: "Naran, Hunza & Skardu Grand Tour",
    type: "local",
    category: "Mountain",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    duration: "11 Days",
    rating: 4.9,
    reviews: 198,
    price: 93500,
    currency: "PKR",
    description: "The ultimate northern Pakistan roadtrip. Traverse Babusar Top, view Nanga Parbat, explore Hunza Valley (Karimabad, Attabad Lake), and discover Skardu.",
    highlights: ["Babusar Pass & Lulusar Lake views", "Attabad Lake boating & jet-ski", "Altit & Baltit ancient fort tours", "Traverse to Cold Desert & Deosai plains"]
  },
  {
    id: 6,
    title: "Explore United Kingdom Group Tour",
    type: "international",
    category: "Cultural",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80",
    duration: "7 Days",
    rating: 4.9,
    reviews: 165,
    price: 497200,
    currency: "PKR",
    description: "Experience the history and charm of Britain. Tour historic London (Big Ben, London Eye, Buckingham Palace) and take a day excursion to Windsor Castle.",
    highlights: ["Guided tour of London highlights", "Thames River cruise with tea", "Day trip to historic Windsor Castle", "Oxford University walking tour"]
  },
  {
    id: 7,
    title: "Explore Japan Heritage Tour",
    type: "international",
    category: "Cultural",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
    duration: "6 Days",
    rating: 4.9,
    reviews: 215,
    price: 593500,
    currency: "PKR",
    description: "Discover Tokyo and Kyoto. Walk through Senso-ji temple, visit Mount Fuji, ride the Shinkansen bullet train, and tour Fushimi Inari shrine.",
    highlights: ["Shinkansen Bullet Train ride", "Senso-ji Temple & Shibuya Crossing", "Mount Fuji 5th Station panoramic view", "Fushimi Inari Torii gate trail"]
  },
  {
    id: 8,
    title: "Explore United States East Coast",
    type: "international",
    category: "Cultural",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80",
    duration: "9 Days",
    rating: 4.8,
    reviews: 184,
    price: 1098500,
    currency: "PKR",
    description: "Tour the famous cities of the US East Coast. Walk Times Square in New York, visit the White House in Washington D.C., and witness Niagara Falls.",
    highlights: ["Statue of Liberty & Times Square tour", "Niagara Falls Maid of the Mist boat tour", "Capitol Hill & Smithsonian Museums", "Philadelphia Liberty Bell visit"]
  }
];
