export const tours = [
  {
    id: 1,
    title: "Baku Group Tour Package",
    type: "international-group",
    category: "Cultural",
    image: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80",
    duration: "5 Days",
    rating: 4.8,
    reviews: 115,
    price: 233800,
    currency: "PKR",
    description: "Explore the stunning architecture of Baku, Azerbaijan. Visit the iconic Flame Towers, Heydar Aliyev Center, and walk the historic streets of Old Town (Icherisheher).",
    highlights: ["Heydar Aliyev Center tour", "Flame Towers & Caspian Boulevard walk", "Icherisheher (Old Baku) guided tour", "Gobustan mud volcanoes day trip"]
  },
  {
    id: 2,
    title: "Thailand Honeymoon Private Tour",
    type: "international-private",
    category: "Beach",
    image: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?auto=format&fit=crop&w=800&q=80",
    duration: "6 Days",
    rating: 4.9,
    reviews: 242,
    price: 387500,
    currency: "PKR",
    description: "A romantic luxury private getaway across Bangkok and Phuket. Enjoy private beach dinners, scenic island hopping, and explore grand Buddhist temples.",
    highlights: ["Private candlelit beach dinner", "Phi Phi Islands speedboat day trip", "Grand Palace & Wat Pho temple tour", "Couples spa treatment in Phuket"]
  },
  {
    id: 3,
    title: "Kalam & Swat Valley Group Adventure",
    type: "local-group",
    category: "Adventure",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    duration: "4 Days",
    rating: 4.7,
    reviews: 86,
    price: 28500,
    currency: "PKR",
    description: "Witness the magnificent pine forests, gushing Swat River, and glacier lakes. Explore Kalam, Ushu Pine Forest, and the breathtaking Mahodand Lake.",
    highlights: ["Explore lush Ushu Pine Forest", "4x4 Jeep track ride to Mahodand Lake", "Fizagat Park and Swat River walk", "Sightseeing at Malam Jabba ski resort"]
  },
  {
    id: 4,
    title: "Himmel Skardu Premium Private Tour",
    type: "local-private",
    category: "Mountain",
    image: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80",
    duration: "5 Days",
    rating: 4.8,
    reviews: 142,
    price: 73500,
    currency: "PKR",
    description: "An exclusive private retreat to Skardu. Visit Shangrila Resort, experience Katpana Cold Desert dune safari, and view Sadpara Lake with a private guide.",
    highlights: ["Shangrila Resort & Lower Kachura Lake", "Katpana Desert dune safari & campfire", "Kharpocho Fort heritage walk", "Day excursion to Deosai National Plains"]
  },
  {
    id: 5,
    title: "Naran, Hunza & Skardu Grand Group Tour",
    type: "local-group",
    category: "Mountain",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
    duration: "11 Days",
    rating: 4.9,
    reviews: 198,
    price: 93500,
    currency: "PKR",
    description: "The ultimate northern Pakistan roadtrip. Traverse Babusar Top, view Nanga Parbat, explore Hunza Valley (Karimabad, Attabad Lake), and discover Skardu.",
    highlights: ["Babusar Pass & Lulusar Lake views", "Attabad Lake boating & jet-ski", "Altit & Baltit ancient fort tours", "Traverse to Cold Desert & Deosai plains"]
  },
  {
    id: 6,
    title: "Europe 3-Countries Grand Group Tour",
    type: "international-group",
    category: "Cultural",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    duration: "7 Days",
    rating: 4.9,
    reviews: 165,
    price: 393500,
    currency: "PKR",
    description: "Tour the historic hearts of France, Germany, and Switzerland. Visit the Eiffel Tower in Paris, explore Heidelberg Castle, and gaze at the Swiss Alps.",
    highlights: ["Eiffel Tower & Seine River Cruise", "Guided tour of Heidelberg Castle", "Scenic drive through the Black Forest", "Mount Titlis cable car excursion"]
  },
  {
    id: 7,
    title: "Japan Private Heritage Tour",
    type: "international-private",
    category: "Cultural",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
    duration: "9 Days",
    rating: 4.9,
    reviews: 215,
    price: 678500,
    currency: "PKR",
    description: "An exclusive private journey through Tokyo, Mount Fuji, and Kyoto. Travel via bullet train and stay in traditional luxury Ryokan inns.",
    highlights: ["Private guide & private vehicle transfers", "Senso-ji Temple & Shibuya Crossing", "Mount Fuji 5th Station panoramic view", "Kyoto tea ceremony & Fushimi Inari trail"]
  },
  {
    id: 8,
    title: "Kashmir & Shogran Valley Group Tour",
    type: "local-group",
    category: "Mountain",
    image: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80",
    duration: "8 Days",
    rating: 4.8,
    reviews: 94,
    price: 56500,
    currency: "PKR",
    description: "Discover the pristine forests of Neelum Valley, walk the lush meadows of Siri Paye, and relax in the beautiful hill station of Shogran.",
    highlights: ["Siri Paye Meadows jeep excursion", "Neelum River bank photography walk", "Keran, Sharda, and Kutton waterfall tours", "Musical bonfire night in Shogran"]
  },
  {
    id: 9,
    title: "Montenegro Private Coast & Alps Tour",
    type: "international-private",
    category: "Beach",
    image: "https://images.unsplash.com/photo-1555992336-03a23c7b20eb?auto=format&fit=crop&w=800&q=80",
    duration: "8 Days",
    rating: 4.8,
    reviews: 73,
    price: 293200,
    currency: "PKR",
    description: "Wander the UNESCO-listed Kotor Bay, explore the rugged Durmitor National Park, and relax on private beaches along the Adriatic Sea.",
    highlights: ["Private yacht tour of Kotor Bay", "Explore old town Budva with local guide", "Hike around Black Lake in Zabljak", "Tara River Canyon zip-lining adventure"]
  },
  {
    id: 10,
    title: "Bangkok & Pattaya Group Tour",
    type: "international-group",
    category: "Beach",
    image: "https://images.unsplash.com/photo-1563492065561-36d319e8fc15?auto=format&fit=crop&w=800&q=80",
    duration: "7 Days",
    rating: 4.7,
    reviews: 132,
    price: 173500,
    currency: "PKR",
    description: "Experience the vibrant city life of Bangkok and the tropical beaches of Pattaya. Includes coral island speed boating and temple tours.",
    highlights: ["Coral Island speedboat trip with lunch", "Alcazar cabaret show tickets", "Wat Arun & Wat Pho temple tour", "Chaophraya River luxury dinner cruise"]
  },
  {
    id: 11,
    title: "Murree & Nathia Gali Private Escape",
    type: "local-private",
    category: "Adventure",
    image: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=800&q=80",
    duration: "5 Days",
    rating: 4.7,
    reviews: 58,
    price: 46500,
    currency: "PKR",
    description: "Enjoy a cool mountain breeze in the Galliyat region. Wander the quiet walking trails of Nathia Gali, visit Ayubia pipeline tracks, and stay in Murree.",
    highlights: ["Nathia Gali pipeline walking track", "Ayubia chairlift ride & picnic", "Mall Road shopping in Murree", "Private vehicle transfers throughout"]
  },
  {
    id: 12,
    title: "Hunza, Skardu & Chillas Private Safari",
    type: "local-private",
    category: "Mountain",
    image: "https://images.unsplash.com/photo-1622218413697-3f9b8df790eb?auto=format&fit=crop&w=800&q=80",
    duration: "10 Days",
    rating: 4.9,
    reviews: 112,
    price: 133200,
    currency: "PKR",
    description: "An exclusive, high-end private safari across the Karakoram. Stay in premium luxury resorts, cross the Hussaini bridge, and tour Karimabad forts.",
    highlights: ["Premium resort stays in Hunza & Skardu", "Private land cruiser Prado transportation", "Attabad Lake private boating tour", "Rakaposhi & Nanga Parbat viewpoints"]
  }
];
